apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

from . import views
from . views import signup
from apps.accounts import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    #path('signup/', views.signup , name='signup'),
    path('lazysignup/', views.lazysignup, name='lazysignup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('switchgroup/', views.switch_lazyuser_group, name='switch_lazyuser_group'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='my_account'),
    # password reset urls
    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url = reverse_lazy('accounts:password_reset_done')
            ), name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'),
            name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url = reverse_lazy('accounts:password_reset_complete')),
            name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'),
            name='password_reset_complete'),
    # password change urls
    path('settings/password/', 
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url = reverse_lazy('accounts:password_change_done')),
            name='password_change'),
    path('settings/password/done/', 
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password_change_done.html'),
            name='password_change_done'),
]


predictDemo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

# Load plotly apps -this triggers their registration
import plotlydash.cml_bcr_abl_ratio
import plotlydash.cml_bcr_abl_ratio_agg
import plotlydash.cml_rec_portrait_model
import plotlydash.cml_rec_prob_model
import plotlydash.cml_rec_prob_model_v2

from django_plotly_dash.views import add_to_session

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('convert/', include('lazysignup.urls')), #convert lazy accounts to real accounts
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('patients/', include('apps.patients.urls', namespace='patients')),
    path('predictions/', include('apps.predictions.urls', namespace='predictions')),
    path('rest/', include('apps.rest.urls', namespace='rest')),
    path('trials/', include('apps.trials.urls', namespace='trials')),
    path('views/', include('apps.dbviews.urls', namespace='dbviews')),
    path('docs/', include('docs.urls')), # third party include

    # django_plotly_dash app
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG: # for serving media files locally
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, User, Group
from django.db import models

""" Override the default representation of user 'username' with 'lastname, firstname""" 
# def get_full_name(self):
#     return self.last_name + ', '+ self.first_name

# User.add_to_class("__str__", get_full_name)


'''Adding additional fields to group'''
Group.add_to_class('description', models.CharField(max_length=180,null=True, blank=True))
Group.add_to_class('ttp_studyId', models.CharField(max_length=180,null=True, blank=True))
Group.add_to_class('ttp_targetIdType', models.CharField(max_length=180,null=True, blank=True))

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    # includ email, last name and first name in login form
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

apps/accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView

from lazysignup.decorators import allow_lazy_user
from rolepermissions.checkers import has_role
from rolepermissions.roles import assign_role, remove_role

from .forms import SignUpForm

# Create your views here.

@allow_lazy_user
def lazysignup(request):
    """
    This view will create a temporary (guest) user account.
    The user is in the group "dept_haematology" and in the group "cml_trial"
    """
    cml_trial = Group.objects.get(id = 1) 
    cml_trial.user_set.add(request.user)
    return redirect('home')


def switch_lazyuser_group(request):
    """
    This view will switch the lazy user from group dept_haematology to trial_cml or the other way
    """

    if has_role(request.user, "trial_cml"):
        remove_role(request.user, "trial_cml")
        assign_role(request.user, "dept_haematology")
    elif has_role(request.user, "dept_haematology"):
        remove_role(request.user, "dept_haematology")
        assign_role(request.user, "trial_cml")
    else:
        assign_role(request.user, "dept_haematology")

    return redirect('home')

def signup(request):
    """
    This view will create a user account
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user, backend = 'django.contrib.auth.backends.ModelBackend')
            return redirect('accounts:my_account')
    else:
        form = SignUpForm()
    return render(request,'accounts/signup.html', {'form':form})


@method_decorator(login_required, name='dispatch')
class UserUpdateView(SuccessMessageMixin, UpdateView):
    """
    This view will update the account information
    """
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'accounts/my_account.html'
    success_message = 'Your user account has been changed successfully!'
    success_url = reverse_lazy('accounts:my_account')

    def get_object(self):
        return self.request.user
    
def setGroup(request):
    dept_haematology = Group.objects.get(id = 1) 
    dept_haematology.user_set.add(request.user)

apps/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<!--Login Form col-lg-4 col-md-6 col-sm-8-->
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                <h3 class="card-title">Log in</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary btn-block">Log in</button>
                </form>
                </div>
                <div class="card-footer text-muted text-center">
                New user? Please contact support-<!-- kommentar@falle -->kks@uniklinikum<!-- kommentar@falle -->-dresden.de
                </div>
            </div>
            <div class="text-center py-2">
                <small>
                <a href="{% url 'accounts:password_reset' %}" class="text-muted">Forgot your password?</a>
                </small>
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

apps/accounts/templates/accounts/my_account.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}My account{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">    
          <li class="breadcrumb-item active">My account</li>
        </ol>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-10">
        <p>Please complete your information.</p>
        <form method="post" novalidate>
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
      </div>
    </div>
    {% if messages %}
    <div class="messages alert alert-success mt-3">
        {% for message in messages %}
        <!--<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>-->
        {{ message }}
        {% endfor %}
    </div>
  </div>
  {% endif %}
{% endblock %}

apps/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Change password{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">    
          <li class="breadcrumb-item active">Change password</li>
        </ol>
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% comment %} {% block breadcrumb %}
    <div class="container">
    <ol class="breadcrumb my-4">    
        <li class="breadcrumb-item active"><a href="{% url 'accounts:password_change' %}">Change password</a></li>
        <li class="breadcrumb-item active">Success</li>
    </ol>
{% endblock %} {% endcomment %}

{% block content %}
  <div class="container">
    <div class="alert alert-success" role="alert">
      <strong>Success!</strong> Your password has been changed!
    </div>
    <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Password changed!</h3>
            <div class="alert alert-success" role="alert">
              You have successfully changed your password! You may now proceed to log in.
            </div>
            <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% bootstrap_form form %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks.

apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Sign up</h3>
                            <form method="post" novalidate>
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-primary">Create an account</button>
                             </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                        Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}