apps/dbviews/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'dbviews'

urlpatterns = [
    #path('diagnostic_values/<int:trial_pk>/', views.sdv_diagnostic_values, name='sdv_diagnostic_values'),
    path('diagnostic_values/<int:trial_pk>/', TrialDiagnosticDetailView.as_view(), name='trial_diagnostic_values'),
    path('medication/<int:trial_pk>/', TrialMedicationDetailView.as_view(), name='trial_medication_values'),
]

apps/trials/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'trials'

urlpatterns = [
    path('list/', TrialListView.as_view(), name='trials_list'),
    path('add/', TrialCreateView.as_view(), name='trials_create'),
    path('delete/<int:trial_pk>/', TrialDeleteView.as_view(), name='trials_delete'),
    path('detail/<int:trial_pk>/', TrialDetailView.as_view(), name='trials_detail'),
    path('edit/<int:trial_pk>/', TrialUpdateView.as_view(), name='trials_update'),
    path('uploads/<int:trial_pk>/', TrialUploadListView.as_view(), name='trials_file_list'),    
    path('upload/<int:trial_pk>/', views.trials_file_upload, name='trials_file_upload'),
    path('upload/detail/<int:document_pk>/', TrialUploadDetailView.as_view(), name='trials_upload_detail'),
    path('upload/edit/<int:document_pk>/', TrialUploadUpdateView.as_view(), name='trials_upload_update'),
    path('upload/delete/<int:document_pk>/', TrialUploadDeleteView.as_view(), name='trials_upload_delete'),

    path('secret/', views.my_secret_view, name='secret'),
]

predictDemo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

# Load plotly apps -this triggers their registration
import plotlydash.cml_bcr_abl_ratio
import plotlydash.cml_bcr_abl_ratio_agg
import plotlydash.cml_rec_portrait_model
import plotlydash.cml_rec_prob_model
import plotlydash.cml_rec_prob_model_v2

from django_plotly_dash.views import add_to_session

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('convert/', include('lazysignup.urls')), #convert lazy accounts to real accounts
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('patients/', include('apps.patients.urls', namespace='patients')),
    path('predictions/', include('apps.predictions.urls', namespace='predictions')),
    path('rest/', include('apps.rest.urls', namespace='rest')),
    path('trials/', include('apps.trials.urls', namespace='trials')),
    path('views/', include('apps.dbviews.urls', namespace='dbviews')),
    path('docs/', include('docs.urls')), # third party include

    # django_plotly_dash app
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG: # for serving media files locally
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/trials/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
import os
# Create your models here.

class Trial(models.Model):
    studyCode = models.CharField(max_length = 20, unique=True)
    name = models.CharField(max_length = 40)
    description = models.TextField(blank = True)
    clinicalTrials = models.CharField(max_length = 40, blank = True)
    eudraCT = models.CharField(max_length = 40, blank = True)
    disease = models.CharField(max_length = 100, blank = True)
    group = models.ForeignKey(Group, on_delete = models.CASCADE, null=True, blank=True)
    hopt_studyid = models.IntegerField(blank = True, null = True)
    createdAt = models.DateTimeField(auto_now_add = True)
    createdBy = models.ForeignKey(User, on_delete = models.CASCADE, default = None)  


    def __str__(self):
        return '%s' % (self.name)

class TrialPermission(models.Model):
    PERMISSION = (
        (0, 'view'),
        (1, 'change (and view)'),
        (2, 'delete, (and view + change'),
        (3, 'admin, (and view + change + delete)')
    )
    trial = models.ForeignKey(Trial, on_delete = models.CASCADE, default = None)
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = None)
    permission = models.IntegerField(choices = PERMISSION, default = 0)
    createdAt = models.DateTimeField(auto_now_add = True)
    createdBy = models.ForeignKey(User, related_name='trial_createdBy', on_delete = models.CASCADE, default = None)

class Document(models.Model):
    document = models.FileField(upload_to = 'documents/trials/%Y/%m/%d')
    description = models.TextField(max_length = 255, blank = True)
    trial = models.ForeignKey(Trial, on_delete = models.CASCADE, default = None)
    uploaded_at = models.DateTimeField(auto_now_add = True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, default = None)

    def filename(self):
        return os.path.basename(self.document.name)

'''
Following method ensures that file will be deleted when document object is deleted
* instance.file – ensures that only the current file is affected
* Passing “false” to instance.file.delete ensures that FileField does not save the model
* Unlike pre_delete, post_delete signal is sent at the end of a model’s delete() method 
and a queryset’s delete() method. This is safer as it does not execute unless the parent 
object is successfully deleted.
'''
@receiver(post_delete, sender=Document)
def submission_delete(sender, instance, **kwargs):
    instance.document.delete(False) 

apps/trials/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', 'description',)

apps/trials/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse,reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from rolepermissions.mixins import HasPermissionsMixin, HasRoleMixin
from predictDemo.roles.mixins import HasObjectPermissionMixin

from .models import Trial, Document
from .forms import DocumentForm
from ..dbviews.models import PatientTrial

# Create your views here.

@method_decorator(login_required, name='dispatch')
class TrialListView(ListView):
    """
    This view will list the trials
    """
    queryset = Trial.objects.order_by('name')
    context_object_name = 'trials_list'
    template_name = 'trials/trials_list.html'

class TrialCreateView(HasRoleMixin, CreateView):
    """
    This view will create a trial
    """
    allowed_roles = 'admin'
    model = Trial
    fields =('studyCode', 'name', 'description', 'clinicalTrials', 'eudraCT')
    template_name = 'trials/trials_create.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.createdBy = self.request.user
        obj.save()        
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trials:trials_detail', kwargs={'trial_pk' : self.object.pk})

class TrialDeleteView(HasObjectPermissionMixin, DeleteView):
    """
    This view will delete the trial
    """
    checker_name = 'delete_trial'
    model= Trial
    template_name = 'trials/trials_delete.html'
    pk_url_kwarg = 'trial_pk'
    success_url = reverse_lazy('trials:trials_list')

class TrialDetailView(HasObjectPermissionMixin, DetailView):
    """
    This view will retrieve the details for a trial
    """
    checker_name = 'access_trial'
    model = Trial
    template_name = 'trials/trials_detail.html'
    pk_url_kwarg = 'trial_pk'

    def get_context_data(self, **kwargs):
            # Call the base implementation first to get a context
            context = super().get_context_data(**kwargs)
            # Add count of patients
            context['countOfPatients'] = PatientTrial.objects.filter(trial_id=self.kwargs['trial_pk']).count()
            # Add dash_context
            trial_id = self.kwargs['trial_pk']
            user_id = self.request.user.id
            context['dash_context'] = {"trial": {"value": trial_id}, "user": {"value": user_id}}
            return context

class TrialUpdateView(HasObjectPermissionMixin, UpdateView):
    """
    This view will update a trial
    """
    #allowed_roles = 'consultant_admin'
    checker_name = 'change_trial'
    model = Trial
    fields =('studyCode', 'name', 'description', 'clinicalTrials', 'eudraCT', 'disease')
    template_name = 'trials/trials_update.html'
    pk_url_kwarg = 'trial_pk'
    context_object_name = 'trial'

    def form_valid(self, form):
        trial = form.save(commit=False)
        trial.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trials:trials_detail', kwargs={'trial_pk' : self.object.pk})

class TrialUploadListView(HasObjectPermissionMixin, DetailView):
    """
    This view will list the documents for selected trial
    """
    checker_name = 'access_trial'
    model = Trial
    template_name = 'trials/trials_file_list.html'
    pk_url_kwarg = 'trial_pk'

def trials_file_upload(request, trial_pk):
    """
    This method will perform a file upload
    """
    trial = get_object_or_404(Trial, pk=trial_pk)

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            fs = form.save(commit=False)
            fs.trial = trial
            fs.uploaded_by = request.user
            fs.save()
            redirect_to = reverse('trials:trials_file_list', kwargs={'trial_pk': trial_pk})
            return redirect(redirect_to)
    else:
        form = DocumentForm()
    return render(request, 'trials/trials_file_upload.html', {
    #return render(request, 'trials/trials_detail.html', {
        'trial': trial,
        'form': form
    })

# protecting media files test
from django_sendfile import sendfile

@login_required
def my_secret_view(request):
    return sendfile(request, "documents/trials/2019/12/16/DESTINY_20180711_Hammersmith.csv", mimetype="text/plain")


class TrialUploadDetailView(HasObjectPermissionMixin, DetailView):
    """
    This view will retrieve the details for a trial
    """
    checker_name = 'access_trial_upload'
    model = Document
    template_name = 'trials/trials_file_detail.html'
    pk_url_kwarg = 'document_pk'

class TrialUploadUpdateView(HasObjectPermissionMixin, UpdateView):
    """
    This view will update a document
    """
    checker_name = 'access_trial_upload'
    model = Document
    fields =('description',)
    template_name = 'trials/trials_file_update.html'
    pk_url_kwarg = 'document_pk'
    context_object_name = 'document'

    def get_success_url(self):
        return reverse_lazy('trials:trials_upload_detail', kwargs={'document_pk' : self.object.pk})

class TrialUploadDeleteView(HasObjectPermissionMixin, DeleteView):
    """
    This view will delete the trial
    """
    checker_name = 'access_trial_upload'
    model = Document
    template_name = 'trials/trials_file_delete.html'
    pk_url_kwarg = 'document_pk'

    def get_success_url(self):
        trial = self.object.trial
        return reverse_lazy('trials:trials_file_list', kwargs={'trial_pk': trial.pk})

apps/trials/templates/trials/trials_breadcrumb.html
<ol class="breadcrumb my-4">
    <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>

    <!-- Details -->    
    {% if request.resolver_match.url_name == "trials_detail" %}
        <li class="breadcrumb-item active">
            <span class="viewdetailslink">Details</span>
        </li>
    {% else %}
        <li class="breadcrumb-item active">
            <a class="viewdetailslink" href="{% url "trials:trials_detail" trial.pk %}">Details</a> 
        </li>
    {% endif %}
    <!-- Documents -->    
    {% if request.resolver_match.url_name == "trials_file_list" %}
        <li class="breadcrumb-item active">
            <span class="documentslink">Documents</span>
        </li>
    {% else %}
        <li class="breadcrumb-item active">
            <a class="documentslink" href="{% url 'trials:trials_file_list' trial.pk %}">Documents</a>
        </li>
    {% endif %}
    <!-- Documents details -->
    {% comment %} {% if request.resolver_match.url_name == "trials_upload_detail" %}
        <li class="breadcrumb-item active" aria-current="page">Document details</li>
    {% endif %} 
    <li class="breadcrumb-item"><a class="dbviewslink" href="">Views</a></li>
    <li class="breadcrumb-item"><a class="permissionlink" href="">Permissions</a></li>{% endcomment %}
</ol>

apps/trials/templates/trials/trials_create.html
{% extends 'base.html' %}
{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}

{% block title %}
  Trials create
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add trial</li>
        </ol>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.media }}
    <div class="row">
      <div class="col-12">
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'trials:trials_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
      </div>
    </div>
  </form>
{% endblock %}

apps/trials/templates/trials/trials_delete.html
{% extends 'base.html' %}
{% load static %}

<!-- Title -->
{% block title %}
  Trials delete
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>
            <li class="breadcrumb-item active" aria-current="page">Delete trial</li>
        </ol>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete the trial with following values?</p>
            <dl class="row">
                <dt class="col-sm-3">Trial name:</dt>
                <dd class="col-sm-9">{{ trial.name }}</dd>

                <dt class="col-sm-3">Study code:</dt>
                <dd class="col-sm-9">{{ trial.studyCode }}</dd>

                <dt class="col-sm-3">Description:</dt>        
                <dd class="col-sm-9">{{ trial.description }}</dd>

                <dt class="col-sm-3"><a href="https://clinicaltrials.gov/">ClinicalTrials.gov:</a></dt>        
                <dd class="col-sm-9">{{ trial.clinicalTrials }}</dd>

                <dt class="col-sm-3">EutraCT:</dt>        
                <dd class="col-sm-9">{{ trial.clinicalTrials }}</dd>

                <dt class="col-sm-3">Created At:</dt>        
                <dd class="col-sm-9">{{ trial.createdAt }}</dd>

                <dt class="col-sm-3">Created by:</dt>        
                <dd class="col-sm-9">{{ trial.createdBy }}</dd>
            </dl>
            <input class="btn btn-success" type="submit" value="Confirm">
            <a href="{% url 'trials:trials_detail' trial.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

apps/trials/templates/trials/trials_detail.html
{% extends 'base.html' %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}
{% load plotly_dash %}

{% block title %}
  Trial detail
{% endblock %}

{% block breadcrumb %}
    <div class="container">
    {% include "trials/trials_breadcrumb.html" %}
{% endblock %}

{% block content %}
    <h2>Details of {{trial.name}} </h2>
    {% can "change_trial" trial user=user as can_change_trial %}
    {% if can_change_trial %}
        <li class="list-inline-item"><a class="changelink" href="{% url 'trials:trials_update' trial.pk %}">Edit</a></li>
    {% else %}
        <li class="list-inline-item"><span class="isDisabled"><a class="changelink">Edit</a></span></li>
    {% endif %}
    {% can "delete_trial" trial user=user as can_delete_trial %}
    {% if can_delete_trial %}
        <li class="list-inline-item"><a class="deletelink" href="{% url 'trials:trials_delete' trial.pk%}">Delete</a></li>
    {% else %}
        <li class="list-inline-item"><span class="isDisabled"><a class="deletelink">Delete</a></span></li>
    {% endif %}

    <hr />
    <dl class="row">
        <dt class="col-sm-3">Trial name:</dt>
        <dd class="col-sm-9">{{ trial.name }}</dd>

        <dt class="col-sm-3">Study code:</dt>
        <dd class="col-sm-9">{{ trial.studyCode }}</dd>

        <dt class="col-sm-3">Description:</dt>        
        <dd class="col-sm-9">{{ trial.description|linebreaks }}</dd>

        <dt class="col-sm-3"><a href="https://clinicaltrials.gov/">ClinicalTrials.gov:</a></dt>        
        <dd class="col-sm-9">{{ trial.clinicalTrials }}</dd>

        <dt class="col-sm-3">EutraCT:</dt>        
        <dd class="col-sm-9">{{ trial.clinicalTrials }}</dd>

        <dt class="col-sm-3">Disease:</dt>        
        <dd class="col-sm-9">{{ trial.disease }}</dd>

        <dt class="col-sm-3">Created At:</dt>        
        <dd class="col-sm-9">{{ trial.createdAt }}</dd>

        <dt class="col-sm-3">Created by:</dt>        
        <dd class="col-sm-9">{{ trial.createdBy }}</dd>
    </dl>
    <hr />

    <!--
    <h2>Permissions</h2>
    {% can "admin_trial" trial user=user as can_admin_trial %}
    <ul class="list-inline">
        {% if can_admin_trial %}
            <li class="list-inline-item"><a class="addlink" href="">Add permission</a></li>
        {% else %}
            <li class="list-inline-item"><span class="isDisabled"><a class="addlink">Add permission</a></span></li>
        {% endif %}
    </ul>
    {% if trial.trialpermission_set.all %}
        <p>In addition to the full access of the creator, access rights are set as follows.</p>
        <table class="table">
            <thead class="thead-inverse">
                <tr>
                    <th>User</th>
                    <th>Permission</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
        {% for permission in trial.trialpermission_set.all %}
            <tr>
                <td>{{ permission.user }}</td>
                <td>{{ permission.get_permission_display }}</td>
                {% if can_admin_trial %}
                    <td><a class="changelink" href="">Edit</a></td>
                    <td><a class="deletelink" href="">Delete</a></td>
                {% else %}
                    <td><span class="isDisabled"><a class="changelink">Edit</a></span></td>
                    <td><span class="isDisabled"><a class="deletelink">Delete</a></span></td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No further permissions available. Only the trial creator has full access.</p>
    {% endif %}
    <div class="alert alert-info" role="alert">
        At present, add, edit and delete permissions aren't implemented in frontend. Changes can be done by admins via Django admin site.
    </div>
    <hr />
    -->
    <h2>Access to research data</h2>
    <p>The trial contains <strong>{{countOfPatients}} patients.</strong></p>
    <ul>
        <li><a href="{% url 'dbviews:trial_diagnostic_values' trial.pk %}">Diagnostic values</a></li>
        <li><a href="{% url 'dbviews:trial_medication_values' trial.pk %}">Treatments</a></li>
    </ul>
    <h2>Data visualization</h2>
    {% plotly_app name="CML_BCR-ABL-Ratio-agg"  initial_arguments=dash_context ratio=1 %}

{% endblock content %}

apps/trials/templates/trials/trials_file_detail.html
{% extends 'base.html' %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}

{% block title %}
  Document detail
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>
            <li class="breadcrumb-item"><a class="viewdetailslink" href="{% url 'trials:trials_detail' document.trial.pk %}">Details</a></li>
            <li class="breadcrumb-item"><a class="documentslink" href="{% url 'trials:trials_file_list' document.trial.pk %}">Documents</a></li>

            <li class="breadcrumb-item active" aria-current="page">Document details</li>
        </ol>
{% endblock %}

{% block content %}
    <h2>Document details</h2>
    <ul class="list-inline">
        <li class="list-inline-item"><a class="changelink" href="{% url 'trials:trials_upload_update' document.pk %}">Edit</a></li>
        <li class="list-inline-item"><a class="deletelink" href="{% url 'trials:trials_upload_delete' document.pk%}">Delete</a></li>
    </ul>
    <hr />
    <hr />
    <dl class="row">
        <dt class="col-sm-3">Document:</dt>
        <dd class="col-sm-9">{{ document.filename }}</dd>
        <dt class="col-sm-3">Description:</dt>
        <dd class="col-sm-9">{{ document.description|linebreaks }}</dd>
        <dt class="col-sm-3">Uploaded at:</dt>
        <dd class="col-sm-9">{{ document.uploaded_at }}</dd>
        <dt class="col-sm-3">Uploaded by:</dt>
        <dd class="col-sm-9">{{ document.uploaded_by }}</dd>
    </dl>
{% endblock content %}

apps/trials/templates/trials/trials_file_list.html
{% extends 'base.html' %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}

{% block title %}
  Trial documents
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        {% include "trials/trials_breadcrumb.html" %}
        {% comment %} <ol class="breadcrumb my-4"> {% endcomment %}
            {% comment %} <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>
            <li class="breadcrumb-item"><a class="viewdetailslink" href="{% url 'trials:trials_detail' trial.pk %}">Details</a></li>
            <li class="breadcrumb-item active" aria-current="page"><span class="documentslink">Documents</span></li>
            <li class="breadcrumb-item"><a class="dbviewslink" href="">Views</a></li>
            <li class="breadcrumb-item"><a class="permissionlink" href="">Permissions</a></li> {% endcomment %}
        </ol>
{% endblock %}

{% block content %}
    <h2>Documents of trial "{{trial.studyCode}}"</h2>
    {% can "change_trial" trial user=user as can_change_trial %}
    <ul class="list-inline">
        {% if can_change_trial %}
            <li class="list-inline-item"><a class="addlink" href="{% url 'trials:trials_file_upload' trial.pk %}">Add file</a></li>
        {% else %}
            <li class="list-inline-item"><span class="isDisabled"><a class="addlink">Add file</a></span></li>
        {% endif %}
    </ul>
    {% if trial.document_set.all %}
        <table class="table">
            <thead class="thead-inverse">
                <tr>
                    <th></th>
                    <th>Document</th>
                    <th>Description</th>
                    <th>Uploaded at</th>
                    <th class="text-right">Uploaded by</th>

                </tr>
            </thead>
            {% for document in trial.document_set.all %}
                <tr>
                    <td>
                        {% if can_change_trial %}
                            <a class="viewdetailslink" href="{% url 'trials:trials_upload_detail' document.pk %}">Details</a>
                        {% else %}
                            <span class="isDisabled"><a class="viewdetailslink">Details</a></span>
                        {% endif %}
                    </td>
                    <td><a class="downloadlink" href="{{ document.document.url }}" target="blank">{{ document.filename }}</a></td>
                    <td>{{ document.description|linebreaks|truncatechars:150 }}</td>
                    <td>{{ document.uploaded_at }}</td>
                    <td class="text-right">{{ document.uploaded_by }}</td>
                    <td></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No documents available.</p>
    {% endif %}
{% endblock content %}

apps/trials/templates/trials/trials_file_update.html
{% extends 'base.html' %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}

{% block title %}
  Document update
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'trials:trials_list' %}">List trials</a></li>
            <li class="breadcrumb-item"><a class="viewdetailslink" href="{% url 'trials:trials_detail' document.trial.pk %}">Details</a></li>
            <li class="breadcrumb-item"><a class="documentslink" href="{% url 'trials:trials_file_list' document.trial.pk %}">Documents</a></li>
            <li class="breadcrumb-item active" aria-current="page">Document update</li>
            <li class="breadcrumb-item"><a class="dbviewslink" href="">Views</a></li>
            <li class="breadcrumb-item"><a class="permissionlink" href="">Permissions</a></li>
        </ol>
{% endblock %}

{% block content %}
    <h2>Document update</h2>
    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ form.media }}
        <div class="row">
        <div class="col-12">
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success">Save changes</button>
            <a href="{% url 'trials:trials_upload_detail' document.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        </div>
        </div>
    </form>
{% endblock %}

apps/trials/templates/trials/trials_list.html
{% extends 'base.html' %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}
<!-- Title -->
{% block title %}
  Trials
{% endblock %}

<!-- breadcrumb -->
{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            {% comment %} <li class="breadcrumb-item"><a href="{% url 'planning:capacity_list' %}">List capacity</a></li> {% endcomment %}
            <li class="breadcrumb-item active" aria-current="page">List trials</li>
        </ol>
{% endblock %}

{% block content %}
    <ul class="list-inline">
    {% if user|has_role:'admin' %}
        <li class="list-inline-item"><a class="addlink" href="{% url 'trials:trials_create' %}">Add trial</a></li>
    {% else %}
        <li class="list-inline-item"><span class="isDisabled"><a class="addlink">Add trial</a></span></li>
    {% endif %}
    </ul>
    <hr>
    <table class="table">
        <thead>
            <th></th>
            <th>Name</th>
            <th>Code</th>
            <th>ClinicalTrials.gov</th>
            <th>EudraCT</th>
            <th>Disease</th>
        </thead>
        <tbody>
            {% for trial in object_list %}
                <tr>
                    <td>
                        {% can "access_trial" trial user=user as can_access_trial %}
                        {% if can_access_trial %}
                            <li class="list-inline-item"><a class="viewdetailslink" href="{% url 'trials:trials_detail' trial.pk %}">Details</a></li>
                            {% else %}
                            <li class="list-inline-item"><span class="isDisabled"><a class="viewdetailslink">Details</a></span></li>
                        {% endif %}
                    </td>
                    <td>{{ trial.name }}</td>
                    <td>{{ trial.studyCode }}</td>
                    <td>{{ trial.clinicalTrials }}</td>
                    <td>{{ trial.eudraCT }}</td>
                    <td>{{ trial.disease }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}