apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

from . import views
from . views import signup
from apps.accounts import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    #path('signup/', views.signup , name='signup'),
    path('lazysignup/', views.lazysignup, name='lazysignup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('switchgroup/', views.switch_lazyuser_group, name='switch_lazyuser_group'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='my_account'),
    # password reset urls
    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url = reverse_lazy('accounts:password_reset_done')
            ), name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'),
            name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url = reverse_lazy('accounts:password_reset_complete')),
            name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'),
            name='password_reset_complete'),
    # password change urls
    path('settings/password/', 
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url = reverse_lazy('accounts:password_change_done')),
            name='password_change'),
    path('settings/password/done/', 
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password_change_done.html'),
            name='password_change_done'),
]


apps/patients/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'patients'

urlpatterns = [
    #path('list/<int:trial_pk>', views.patients_list, name='patients_list'),
    path('search', views.patients_search, name='patients_search'),
    path('patient', views.patient_mdat_view, name='patient_mdat_view'),
    path('patient/bcrabl', views.patient_mdat_view_bcrabl, name='patient_mdat_view_bcrabl'),
    path('patient/treatment', views.patient_mdat_view_treatment, name='patient_mdat_view_treatment'),
]

apps/predictions/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'predictions'

urlpatterns = [
    path('all/', PredictionListView.as_view(), name='prediction_all_list'),
    path('detail/<int:prediction_pk>/', PredictionDetailView.as_view(), name='prediction_detail'),
    path('list/', views.prediction_list, name='prediction_list'),
    path('create/recurrence_prob/', views.create_magpie_prediction_recurrence_prob, name='prediction_create_recurrence_prob'),
    path('create/modelfit/', views.create_magpie_prediction_modelfit, name='prediction_create_modelfit'),
    path('magpie_download/<int:prediction_id>/', views.magpie_download_jobresults, name='magpie_download_jobresults'),
]

apps/trials/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'trials'

urlpatterns = [
    path('list/', TrialListView.as_view(), name='trials_list'),
    path('add/', TrialCreateView.as_view(), name='trials_create'),
    path('delete/<int:trial_pk>/', TrialDeleteView.as_view(), name='trials_delete'),
    path('detail/<int:trial_pk>/', TrialDetailView.as_view(), name='trials_detail'),
    path('edit/<int:trial_pk>/', TrialUpdateView.as_view(), name='trials_update'),
    path('uploads/<int:trial_pk>/', TrialUploadListView.as_view(), name='trials_file_list'),    
    path('upload/<int:trial_pk>/', views.trials_file_upload, name='trials_file_upload'),
    path('upload/detail/<int:document_pk>/', TrialUploadDetailView.as_view(), name='trials_upload_detail'),
    path('upload/edit/<int:document_pk>/', TrialUploadUpdateView.as_view(), name='trials_upload_update'),
    path('upload/delete/<int:document_pk>/', TrialUploadDeleteView.as_view(), name='trials_upload_delete'),

    path('secret/', views.my_secret_view, name='secret'),
]

predictDemo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

# Load plotly apps -this triggers their registration
import plotlydash.cml_bcr_abl_ratio
import plotlydash.cml_bcr_abl_ratio_agg
import plotlydash.cml_rec_portrait_model
import plotlydash.cml_rec_prob_model
import plotlydash.cml_rec_prob_model_v2

from django_plotly_dash.views import add_to_session

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('convert/', include('lazysignup.urls')), #convert lazy accounts to real accounts
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('patients/', include('apps.patients.urls', namespace='patients')),
    path('predictions/', include('apps.predictions.urls', namespace='predictions')),
    path('rest/', include('apps.rest.urls', namespace='rest')),
    path('trials/', include('apps.trials.urls', namespace='trials')),
    path('views/', include('apps.dbviews.urls', namespace='dbviews')),
    path('docs/', include('docs.urls')), # third party include

    # django_plotly_dash app
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG: # for serving media files locally
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictDemo/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
    <div class="container">
        <h2>Application</h2>
        <p>This demo server relates to the publication <strong>Hoffmann et al. "Data integration between clinical research and patient care: a framework for context-depending data sharing and in silico predictions"</strong>, submitted for publication to PLOS Digital Health (2022). This demo prototype examplifies how data analytic results, particularly in silico predictions, can be seamlessly integrated into workflows for simultaneous use in research an clinical care routines in aspecific hospital setting.</p>
        <h2>Contact</h2>
        <p>Institute for Medical Informatics and Biometry [<a href="https://tu-dresden.de/med/mf/imb">homepage</a>]<br />
Medizinische Fakultät Carl Gustav Carus, Technische Universität Dresden<br/>
If you have any questions or recommendations please contact Katja Hoffmann. <p>
        <h2>Disclaimer</h2>
        <p>The demo server is provided to the research community in good faith without guarantees of any kind.</p>
    </div>
{% endblock content %}

predictDemo/templates/base.html
{% load static %}
<!DOCTYPE html>
{% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title%}</title>
        {% bootstrap_css %} {# Embed Bootstrap CSS #}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block stylesheet %}{% endblock stylesheet%}
        {% bootstrap_javascript jquery='full' %} {# Embed Bootstrap JS+jQuery #}
    </head>

<body>
    {% block body %}
        <!-- Page container (Nav + Content + Footer ) -->
        <div class="page-container">
            <!-- Content Wrap (Nav + Content ) -->
            <div class="content-wrap">
                <!--Nav bar -->
                <nav class="navbar navbar-expand-lg">
                    <div class="container">
                        <!-- Toggler bar -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="true" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <!-- Username right and Dropdown menu for account settings-->
                        <div class="collapse navbar-collapse" id="mainMenu">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'home' %}">
                                    Home
                                    </a>
                                </li>
                            {% if user.is_authenticated %}
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="ForClinicians" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        For Clinic
                                        </a>
                                        <!--For clinician menu-->
                                        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ForClinicians">
                                            {% if user|has_role:'dept_haematology'%}
                                            <a class="dropdown-item" href="{% url 'patients:patients_search' %}">Request patient data</a>
                                            {% else %}
                                            <span class="isDisabled"><a class="dropdown-item" href="">Request patient data</a></span>
                                            {% endif %}
                                        </div>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="ForResearcher" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        For Research
                                        </a>
                                        <!--For researcher menu-->
                                        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ForResearcher">
                                            <!-- <a class="dropdown-item" href="{% url 'predictions:prediction_all_list' %}">Predictions</a> -->
                                            {% if user|has_role:'trial_cml'%}
                                            <a class="dropdown-item" href="{% url 'trials:trials_list' %}">Trials</a>
                                            {% else %}
                                            <span class="isDisabled"><a class="dropdown-item" href="">Trials</a></span>
                                            {% endif %}
                                        </div>                                
                                    </li>
                                <!-- Admin menu for staff-->
                                {% if user.is_staff %}
                                    <li><a class="nav-link" href="{% url 'admin:index' %}" target= "-blank">Admin</a></li>
                                    <li><a class="nav-link" href="{% url 'docs_root' %}" target= "-blank">Docs</a></li>
                                {% endif %}
                                </ul>
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item dropdown">
                                        {% if not user|is_lazy_user %}
                                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            Logged in as {{ user.username }}
                                            </a>
                                        {% else %}
                                            {% if user|has_role:'dept_haematology'%}
                                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            Logged in as guest physician
                                            </a>
                                            {% elif user|has_role:'trial_cml'%}
                                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            Logged in as guest researcher
                                            </a>
                                            {% endif %}
                                        {% endif %}
                                        <!--account setting-->
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                            {% if not user|is_lazy_user %}
                                                <a class="dropdown-item" href="{% url 'accounts:my_account' %}">My account</a>
                                                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
                                            {% else %}
                                                {% if user|has_role:'dept_haematology'%}
                                                    <a class="dropdown-item" href="{% url 'accounts:switch_lazyuser_group' %}">Switch to a guest researcher account.</a>
                                                {% elif user|has_role:'trial_cml'%}
                                                    <a class="dropdown-item" href="{% url 'accounts:switch_lazyuser_group' %}">Switch to a guest physician account.</a>
                                                {% endif %}
                                            {% endif %}
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                                        </div>
                                    </li>
                                </ul>
                            {% else %}
                                <a class="nav-link menu-right" href="{% url 'accounts:login' %}">
                                Log in
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
                <div id="container">
                    <!--breadcrumb-->
                    {% block breadcrumb %}
                    {% endblock breadcrumb %}
                    <!--content-->
                    {% block content %}
                    {% endblock content%}
                </div>
            </div> <!-- End of Content wrap (Nav + Content) -->

            <!-- Footer -->
            <footer class="page-footer font-small">
                <div class="footer">
                    <hr>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 text-center">
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a href="{% url 'home' %}">
                                            <img src={% static "images/prediCt_logo_transparent.png" %} width="70" alt="PrediCt"> 
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://www.eracosysmed.eu/" target="_blank">
                                            <img src={% static "images/eracosysmedLogo-1-750x410.jpg" %} width="70" alt="EracoSysMed">
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://ec.europa.eu/commission/index_de" target="_blank">
                                            <img src={% static "images/ec-logo-horiz-web_en.jpg" %} width="150" alt="European Commission">
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://tu-dresden.de/" target="_blank">
                                            <img src={% static "images/TU_Dresden_Logo_blau_HKS41.png" %} width="100" alt="Technische Universität Dresden">
                                        </a>
                                    </li>
                                    <li class="list-inline-item" style="text-align: right">
                                        <a href="{% url 'about' %}">About</a>
                                    </li>
                                    <li class="list-inline-item" style="text-align: right">
                                        <a href="{% url 'docs_root' %}" target= "-blank" >Documentation</a>                                        
                                    </li>
                                </ul>  
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        <!-- End of page container-->
        </div>
    {% endblock body%}
</body>
</html>

predictDemo/templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load i18n lazysignup_tags %}
{% load permission_tags %}

{% block title %}prediCt{% endblock %}
{% block content %}
    <div class="container">
      <div class="jumbotron">
        <div class=".div-headline">
          {% if  not user.is_authenticated %}
          <h1>Welcome to the demonstrator</h1>
          <br/>
          <h4>Data integration between clinical research and patient care:</h4>
          <h4>a framework for context-depending data sharing and in silico predictions</h4>
          <br/>
          <a class="btn btn-lg btn-info" href="{% url 'accounts:lazysignup' %}">Try it out</a>
          <a class="btn btn-lg btn-primary" href="{% url 'accounts:login' %}">Login</a>
          {% else %}
          <h1>Welcome to the demonstrator</h1>
          <br/>
          <h4>Data integration between clinical research and patient care:</h4>
          <h4>a framework for context-depending data sharing and in silico predictions</h4>
          <br/>
          {% endif %}
        </div>
      </div>
      {% if user|is_lazy_user%}
      <div class="card border-info mb-0">
        <div class="card-body">
          <h5 class="card-title">Account Information</h5>
          {% if user|has_role:'dept_haematology'%}
            <p class="lead">Your are logged in as <strong class="text-danger font-weight-bold">attending (guest) physician from the haematology department of a clinic</strong>.</p>
            <p class="leead">Would you like to login as guest researcher?</p>
            <a class="btn btn-lg btn-primary" href="{% url 'accounts:switch_lazyuser_group' %}">Switch to a guest researcher account.</a>
          {% elif user|has_role:'trial_cml'%}
            <p class="lead">Your are logged in as <strong class="text-danger font-weight-bold">guest researcher with permission to access to the "CML trial"</strong>.</p>
            <p class="leead">Would you like to login as attending (guest) physician?</p>
            <a class="btn btn-lg btn-primary" href="{% url 'accounts:switch_lazyuser_group' %}">Switch to a guest physician account.</a>
          {% endif %}
        </div>
      </div>
      {% endif %}
{% endblock content %}}