apps/patients/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'patients'

urlpatterns = [
    #path('list/<int:trial_pk>', views.patients_list, name='patients_list'),
    path('search', views.patients_search, name='patients_search'),
    path('patient', views.patient_mdat_view, name='patient_mdat_view'),
    path('patient/bcrabl', views.patient_mdat_view_bcrabl, name='patient_mdat_view_bcrabl'),
    path('patient/treatment', views.patient_mdat_view_treatment, name='patient_mdat_view_treatment'),
]

apps/predictions/urls.py
from django.urls import path

from . import views
from . views import *

app_name = 'predictions'

urlpatterns = [
    path('all/', PredictionListView.as_view(), name='prediction_all_list'),
    path('detail/<int:prediction_pk>/', PredictionDetailView.as_view(), name='prediction_detail'),
    path('list/', views.prediction_list, name='prediction_list'),
    path('create/recurrence_prob/', views.create_magpie_prediction_recurrence_prob, name='prediction_create_recurrence_prob'),
    path('create/modelfit/', views.create_magpie_prediction_modelfit, name='prediction_create_modelfit'),
    path('magpie_download/<int:prediction_id>/', views.magpie_download_jobresults, name='magpie_download_jobresults'),
]

predictDemo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

# Load plotly apps -this triggers their registration
import plotlydash.cml_bcr_abl_ratio
import plotlydash.cml_bcr_abl_ratio_agg
import plotlydash.cml_rec_portrait_model
import plotlydash.cml_rec_prob_model
import plotlydash.cml_rec_prob_model_v2

from django_plotly_dash.views import add_to_session

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('convert/', include('lazysignup.urls')), #convert lazy accounts to real accounts
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('patients/', include('apps.patients.urls', namespace='patients')),
    path('predictions/', include('apps.predictions.urls', namespace='predictions')),
    path('rest/', include('apps.rest.urls', namespace='rest')),
    path('trials/', include('apps.trials.urls', namespace='trials')),
    path('views/', include('apps.dbviews.urls', namespace='dbviews')),
    path('docs/', include('docs.urls')), # third party include

    # django_plotly_dash app
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

if settings.DEBUG: # for serving media files locally
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/predictions/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Model(models.Model):
    modelName = models.CharField(max_length = 40)
    magpieModelId = models.IntegerField(unique = True)
    active = models.BooleanField(default = True)
    doi = models.CharField(max_length = 250, blank = True, null = True)
    description = models.TextField(max_length = 4000, blank = True, null = True)

    def __str__(self):
        return '%s' % (self.modelName)

class Dash(models.Model):
    appname = models.CharField(max_length = 2000)

    def __str__(self):
        return '%s' % (self.appname)

class Project(models.Model):
    model = models.ForeignKey(Model, on_delete = models.CASCADE) 
    projectName = models.CharField(max_length = 200)
    magpieProjectId = models.IntegerField(unique = True)
    dash = models.ForeignKey(Dash, on_delete = models.CASCADE, blank = True, null = True)
    description = models.TextField(max_length = 4000, blank = True, null = True)
    
    def __str__(self):
        return '%s' % (self.projectName)

class Prediction(models.Model):
    STATUS = (
        (0, 'started'),
        (1, 'finished'),
        (2, 'failed'),
    )
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    targetId = models.CharField(max_length = 40)
    magpieJobId = models.IntegerField(null=True, default = True)
    status = models.IntegerField(choices = STATUS, default = 0)
    createdAt = models.DateTimeField(auto_now_add = True)
    #createdBy = models.ForeignKey(User, on_delete = models.CASCADE)

apps/predictions/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Max, Q
#from django.http import HttpResponse
from django.shortcuts import redirect, render

from django_pivot.pivot import pivot

from djqscsv import write_csv

from .models import Prediction, Project
from .tables import *

from ..dbviews.models import Diagnostic, TreatMedication

from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin, SingleTableView
from django_tables2.export.views import ExportMixin

import json
import os
import requests
import subprocess

class PredictionListView(SingleTableMixin, ListView):
    """
    This view lists predictions
    """
    queryset = Prediction.objects.all().order_by('-id')
    context_table_name = 'predictionListTable'
    table_class = PredictionListTable
    table_pagination = {"per_page": 10}
    template_name = 'predictions/prediction_all_list.html'

class PredictionDetailView(DetailView):
    """
    This view displays detail information of a prediction
    """
    model = Prediction
    template_name = 'predictions/prediction_detail.html'
    pk_url_kwarg = 'prediction_pk'

    def get_context_data(self, *args, **kwargs):
        # passing prediction_id as initial value to context
        context = super().get_context_data(*args, **kwargs)
        prediction_id = self.kwargs['prediction_pk']
        # dash app name
        prediction = Prediction.objects.get(id = prediction_id)
        context['dash_app'] = prediction.project.dash.appname
        # initial value
        dash_context_simple = {"prediction_id": {"value": prediction_id}, "dropdown": {"value": "simple"}}
        dash_context_expert = {"prediction_id": {"value": prediction_id}, "dropdown": {"value": "expert"}}
        context['dash_context_simple'] = dash_context_simple
        context['dash_context_expert'] = dash_context_expert
        return context

@login_required
def prediction_list(request):
    # get patient data from session
    patient_data = json.loads(request.session['patient_data'])
    targetId = request.session['targetId']
    #domain = request.session['domain']
    predictions = Prediction.objects.filter(targetId = targetId).order_by('-id')
    #initial_arguments for dash app
    dash_context_dict = {}
    for prediction in predictions:
        prediction_id = prediction.pk
        dash_context_simple = {"prediction_id": {"value": prediction_id}, "dropdown": {"value": "simple"}}
        dash_context_expert = {"prediction_id": {"value": prediction_id}, "dropdown": {"value": "expert"}}
        dash_context_dict[prediction_id] = {}
        dash_context_dict[prediction_id]['simple'] = dash_context_simple
        dash_context_dict[prediction_id]['expert'] = dash_context_expert

    return render(request, 'predictions/prediction_list.html', {
        'patient_data' : patient_data,
        'targetId': targetId,
        #'domain': domain,
        'predictions': predictions,
        'dash_context_dict': dash_context_dict,
        })

@login_required
def create_magpie_prediction_recurrence_prob(request):
    # new prediction object
    targetId = request.session['targetId']
    projectId = 6

    n = Prediction.objects.create(project_id = projectId, targetId = targetId)
    prediction_id = n.id

    # save patdata
    if not os.path.exists(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', str(prediction_id)))):
        os.makedirs(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', str(prediction_id))))

    treatMedication = TreatMedication.objects.filter(targetId = targetId)
    with open(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_medi.csv'))), 'wb') as csv_file:
        write_csv(treatMedication, csv_file, delimiter=';')
    
    diagnostic = Diagnostic.objects.filter(targetId = targetId, diagType_id = 1) # diagType = PCR - BCR-ABL/ABL

    #exclude observations after stop
    diagnostic = diagnostic.filter(sampleDate__lte = treatMedication.filter(medScheme='half dose')[0].dateEnd)

    diag_pivot = pivot(diagnostic, ['sampleId', 'sampleDate'], 'parameter_id__parameterName', 'value', aggregation=Max)
    with open(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_pcr.csv'))), 'wb') as csv_file:
        write_csv(diag_pivot, csv_file, delimiter=';')

    # create magpie job
    magpie_url = settings.MAGPIE_URL
    magpie_user = settings.MAGPIE_USER
    magpie_password = settings.MAGPIE_PASSWORD

    # magpie ids for project and model
    project = Project.objects.get(id = projectId)
    magpie_project_id = str(project.magpieProjectId)
    magpie_model_id = str(project.model.magpieModelId)

    df_pcr = os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_pcr.csv')))
    df_treat = os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_medi.csv')))

    args = [magpie_user, magpie_password, magpie_url, magpie_project_id, magpie_model_id, df_pcr, df_treat]

    command = 'Rscript'
    path2script = os.path.join(os.path.dirname(__file__), 'Rscripts/magpie_create_job.R')
    cmd = [command, path2script] + args

    x = None
    try:
        x = subprocess.check_output(cmd, universal_newlines = True)
    except subprocess.CalledProcessError as e:
        x = e.output

    # update prediction with magpie_job_id
    stdout_dict = {}
    i = 0
    for line in x.split('\n'):
        print("%r" % line)
        i = i + 1
        stdout_dict[i] = line
    magpie_job_id = stdout_dict[3]

    Prediction.objects.filter(id = prediction_id).update(magpieJobId = magpie_job_id)

    return redirect('predictions:prediction_list')

@login_required
def create_magpie_prediction_modelfit(request):
    # new prediction object
    targetId = request.session['targetId']
    projectId = 5

    n = Prediction.objects.create(project_id = projectId, targetId = targetId)
    prediction_id = n.id

    # save patdata
    if not os.path.exists(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', str(prediction_id)))):
        os.makedirs(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', str(prediction_id))))

    treatMedication = TreatMedication.objects.filter(targetId = targetId)
    with open(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_medi.csv'))), 'wb') as csv_file:
        write_csv(treatMedication, csv_file, delimiter=';')

    diagnostic = Diagnostic.objects.filter(targetId = targetId, diagType_id = 1) # diagType = PCR - BCR-ABL/ABL 
    diag_pivot = pivot(diagnostic, ['sampleId', 'sampleDate'], 'parameter_id__parameterName', 'value', aggregation=Max)
    with open(os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_pcr.csv'))), 'wb') as csv_file:
        write_csv(diag_pivot, csv_file, delimiter=';')

    # create magpie job
    magpie_url = settings.MAGPIE_URL
    magpie_user = settings.MAGPIE_USER
    magpie_password = settings.MAGPIE_PASSWORD

    # magpie ids for project and model
    project = Project.objects.get(id = projectId)
    magpie_project_id = str(project.magpieProjectId)
    magpie_model_id = str(project.model.magpieModelId)

    df_pcr = os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_pcr.csv')))
    df_treat = os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', os.path.join(str(prediction_id), 'patdata_medi.csv')))

    args = [magpie_user, magpie_password, magpie_url, magpie_project_id, magpie_model_id, df_pcr, df_treat]

    command = 'Rscript'
    path2script = os.path.join(os.path.dirname(__file__), 'Rscripts/magpie_create_job.R')
    cmd = [command, path2script] + args

    x = None
    try:
        x = subprocess.check_output(cmd, universal_newlines = True)
    except subprocess.CalledProcessError as e:
        x = e.output

    # update prediction with magpie_job_id
    stdout_dict = {}
    i = 0
    for line in x.split('\n'):
        print("%r" % line)
        i = i + 1
        stdout_dict[i] = line
    magpie_job_id = stdout_dict[3]

    Prediction.objects.filter(id = prediction_id).update(magpieJobId = magpie_job_id)

    return redirect('predictions:prediction_list')

@login_required
def magpie_download_jobresults(request, prediction_id):
    # get prediction by id
    prediction = Prediction.objects.get(id = prediction_id)

    # variable number of args in a list
    magpie_url = settings.MAGPIE_URL
    magpie_user = settings.MAGPIE_USER
    magpie_password = settings.MAGPIE_PASSWORD
    magpie_project_id = str(prediction.project.magpieProjectId)
    magpie_model_id = str(prediction.project.model.magpieModelId)
    magpie_job_id = str(prediction.magpieJobId)
    media_dir = os.path.join(settings.MEDIA_ROOT, os.path.join('documents/predictions', str(prediction_id)))

    # run R script for job download
    command = 'Rscript'
    #path2script = '/usr/local/www/djangoprojects/predictDemo/apps/predictions/Rscripts/magpie_download_jobresults.R'
    path2script = os.path.join(os.path.dirname(__file__), 'Rscripts/magpie_download_jobresults.R')
    args = [magpie_user, magpie_password, magpie_url, magpie_project_id, magpie_model_id, magpie_job_id, media_dir]

    cmd = [command, path2script] + args

    x = None
    try:
        x = subprocess.check_output(cmd, universal_newlines = True)
    except subprocess.CalledProcessError as e:
        x = e.output

    # update prediction with magpie_job_id
    stdout_dict = {}
    i = 0
    for line in x.split('\n'):

apps/predictions/templates/predictions/prediction_all_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load django_tables2 %}

<!-- Title -->
{% block title %}
  Predictions
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item active">Predicitions</li>
        </ol>
{% endblock %}

{% block content %}
    {% render_table predictionListTable %}
{% endblock %}

apps/predictions/templates/predictions/prediction_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load django_tables2 %}
{% load plotly_dash %}

<!-- Title -->
{% block title %}
  Prediction detail
{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'predictions:prediction_all_list' %}">Predicitions</a></li>
            <li class="breadcrumb-item active">Detail</li>
        </ol>
{% endblock %}

{% block content %}
    <div class="card">
        <h5 class="card-header">
            Prediction
        </h5>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">Prediction id:</dt>
                <dd class="col-sm-9">{{ object.id }}</dd>

                <dt class="col-sm-3">MAGPIE Job id:</dt>
                <dd class="col-sm-9">{{ object.magpieJobId}}</dd>

                <dt class="col-sm-3">MAGPIE Model (id):</dt>
                <dd class="col-sm-9">{{ object.project.model}} ({{ object.project.model.magpieModelId}})</dd>

                <dt class="col-sm-3">MAGPIE Project id:</dt>
                <dd class="col-sm-9">{{ object.project}}</dd>

                <dt class="col-sm-3">Patient (target id):</dt>
                <dd class="col-sm-9">{{ object.targetId}}</dd>

                <dt class="col-sm-3">Status:</dt>
                <dd class="col-sm-9">{{ object.get_status_display}}</dd>

                <dt class="col-sm-3">Created at:</dt>
                <dd class="col-sm-9">{{ object.createdAt}}</dd>

                <dt class="col-sm-3">Reference to the model:</dt>
                <dd class="col-sm-9"><a href='{{ prediction.project.model.doi }}'>{{ prediction.project.model.doi }}<a></dd>
            </dl>
        
        </diV>
    </div>
     
    {% plotly_app name=dash_app initial_arguments=dash_context_simple ratio=0.5 %}
    {% plotly_app name=dash_app initial_arguments=dash_context_expert ratio=0.6 %}
{% endblock %}

apps/predictions/templates/predictions/prediction_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load django_tables2 %}
{% load i18n lazysignup_tags %}
{% load querystring from django_tables2 %}
{% load plotly_dash %}

{% block breadcrumb %}
    <div class="container-fluid">
        <div class = "container">
            <ol class="breadcrumb my-4">
                <li class="breadcrumb-item"><a href="{% url 'patients:patients_search' %}">Step 1: Search patient</a></li>
                <li class="breadcrumb-item active">Step 2: Retrieve patient-specific medical data and model predictions</li>
            </ol>
{% endblock %}

{% block content %}

{% if targetId == None %}
<div class="alert alert-danger" role="alert">
  The given person could not be surely identified.
</div>
<a href="{% url 'patients:patients_search' %}" class="btn btn-secondary">Return to Patient search</a>
{% else %}

<div class="alert alert-info" role="alert">
  Patient: <strong>{{ patient_data.lastName }}, {{ patient_data.firstName }}  born on {{ patient_data.birthdate }} in {{ patient_data.birthplace }} ({{ patient_data.gender }})</strong>
</div>

<!-- Submenu-->
<p>
  <a class="btn btn-secondary" href="{% url 'patients:patient_mdat_view' %}">Dashboard</a>
  <a class="btn btn-secondary" href="{% url 'patients:patient_mdat_view_treatment' %}">TableView "Treatments"</a>
  <a class="btn btn-secondary" href="{% url 'patients:patient_mdat_view_bcrabl' %}">TableView "BCR-ABL / ABL"</a>
  <a class="btn btn-primary" href="{% url 'predictions:prediction_list' %}">All Predictions</a>
</p>

<ul class="list-inline">
  {% if user.is_authenticated and not user|is_lazy_user %}
      <li class="list-inline-item"><a class="addlink" href="{% url 'predictions:prediction_create_recurrence_prob' %}">New prediction of recurrence probability</a></li>
      <li class="list-inline-item"><a class="addlink" href="{% url 'predictions:prediction_create_modelfit' %}">New modelfit after cessation</a></li>
  {% else %}
      <li class="list-inline-item"><span class="isDisabled"><a class="addlink">New prediction of recurrence probability</a></span></li>
      <li class="list-inline-item"><span class="isDisabled"><a class="addlink">New modelfits after cessation (32 fits)</a></span></li>
  {% endif %}
</ul>
<hr>
<p>Model predictions are listed below.</p>
<!-- List all predictions with details -->
<div id="all_predicts">
  {% for prediction in predictions %}
    <div class="card">
      <div class="card-header {% if prediction.status == 0 %} bg-light {% elif prediction.status == 1 %} bg-info {% else %} bg-danger {% endif %}" id="predict_{{ prediction.pk }}">
          <a class="btn collapsed" data-toggle="collapse" data-target="#collapse_{{ prediction.pk }}" aria-expanded="false" aria-controls="collapse_{{ prediction.pk }}">
            <strong>{{ prediction.project }}</strong>, created at <strong>{{ prediction.createdAt }}</strong>
          </a>
      </div>
      <div id="collapse_{{ prediction.pk }}" class="collapse" aria-labelledby="heading_{{ prediction.pk }}">
        <div class="card-body">
          {% for key, dash_value in dash_context_dict.items %}
            {% if key == prediction.pk %}
              {% if prediction.status == 0 %}
                <a class="downloadlink" href="{% url 'predictions:magpie_download_jobresults' prediction.pk %}">Download prediction results</a>
              {% endif %}
              {% if prediction.status == 1 %}
                {% plotly_app name=prediction.project.dash.appname initial_arguments=dash_value.simple ratio=0.45 %}
                <div class = "row">
                  <div class = "col">
                    <a class="btn btn-primary" data-toggle="collapse" href="#collapseModel1Expert" role="button" aria-expanded="false" aria-controls="collapseModel1Expert">
                      Show/Hide Expert View
                    </a>
                  </div>
                  {% if prediction.project.model.doi %}
                  <div col="col text-right">
                    Reference to the model: <a href='prediction.project.model.doi'>{{ prediction.project.model.doi }}<a>
                    </div>
                </div>
                {% endif %}
                <div class="collapse" id="collapseModel1Expert">
                  <div class="card-body">
                    {% plotly_app name=prediction.project.dash.appname initial_arguments=dash_value.expert ratio=0.6%}
                  </div>
                </div> 
              {% endif %}
              {% if prediction.status == 2 %}
                The prediction failed while proceeding.
              {% endif %}
            {% endif %}     
          {% endfor %}
          Prediction ID: {{ prediction.id }}, 
          Magpie ProjectId: {{ prediction.project.magpieProjectId }}, 
          Magpie JobId: {{ prediction.magpieJobId }}
        </div>
      </div>
    </div>
  {% empty %}
      No predictions available.
  {% endfor %}
</div>

{% endif %}
</div>
{% endblock content %}